### ISSUE TITLE
github action: run "sudo apt update" before "sudo apt install" for Ubuntu CMake task

### ISSUE THREAD

**Issue by mcuee** [libusb/hidapi#312]
I was looking at the error log and it seems that github action script needs minor modification. The step "Install dependencies" may fail without "sudo apt update" first.

```
   steps:
    - uses: actions/checkout@v2
      with:
        path: hidapisrc
    - name: Install dependencies
      run: sudo apt install libudev-dev libusb-1.0-0-dev
```

```
Run sudo apt install libudev-dev libusb-1.0-0-dev

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libusb-1.0-doc
The following NEW packages will be installed:
  libudev-dev libusb-1.0-0-dev libusb-1.0-doc
0 upgraded, 3 newly installed, 0 to remove and 13 not upgraded.
Need to get 257 kB of archives.
After this operation, 2067 kB of additional disk space will be used.
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libudev-dev amd64 245.4-4ubuntu3.7
  404  Not Found [IP: 40.119.46.219 80]
Get:2 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libusb-1.0-0-dev amd64 2:1.0.23-2build1 [64.4 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libusb-1.0-doc all 2:1.0.23-2build1 [172 kB]
Fetched 237 kB in 0s (3066 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_245.4-4ubuntu3.7_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
